### ISSUE TITLE
p adic numbers

### ISSUE THREAD

**Issue by the-codeboy** [the-codeboy/mensabot#73]
Feature request by @Gobidev 

https://en.wikipedia.org/wiki/P-adic_number

**Comment by the-codeboy** [comment]
I don't really know what you want me to do here. Could you clarify @Gobidev ?

**Comment by Gobidev** [comment]
You can close this issue, this feature is completely unnecessary and hard to implement

**Comment by the-codeboy** [comment]
maybe in the rust rewrite
